### ISSUE TITLE
make the aws region configurable

### ISSUE THREAD

**Issue by rvdwijngaard** [Tim-B/grunt-aws-lambda#14]
The region for aws sdk is not configurable. The file 'lambda_deploy.js' has a hard coded value of us-west-1 for the region. As a result it is not possible to deploy to any other aws region.

**Comment by jagedn** [comment]
as far I know you can configure your region into options:

grunt.initConfig({
   lambda_deploy: {
        myprofile : {
	    arn : 'arn:aws:lambda:eu-west-1:xxxxxx:function:parseCustom',
            options: {
              region : 'eu-west-1'   ,
              handler : 'parseCustom'
            },
            function : 'parseCustom'
        }
    }   
}

**Comment by Tim-B** [comment]
The options here:

```
        var options = this.options({
            profile: null,
            region: 'us-east-1',
            timeout: null,
            memory: null
        });
```

Are just defaults, you be able to override them in your grunt config as jagedn suggested.

If that doesn't work let me know.
