### ISSUE TITLE
Hidden files are not packaged

### ISSUE THREAD

**Issue by satyasrikantmantha** [Tim-B/grunt-aws-lambda#17]
I have a hidden environment file call ".env" which is used to bootstrap environment variables using package "node-env-file", however I notice that the file is not being packaged.

**Comment by satyasrikantmantha** [comment]
I think you need to update the package code to include, when you make a call to bulk function line 64 tasks/lambda_package.js. 

Look for this thread 
https://github.com/archiverjs/node-archiver/issues/110

**Comment by Tim-B** [comment]
Thanks for the bug report, I just pushed out a new version which I think will address this. Let me know how you go.

**Comment by satyasrikantmantha** [comment]
Thanks it works, however it also includes the .npmignore file, 
Small update to .npmignore in your documentation, now it should also contain and exclude for this file for packaging:
````
.npmignore
event.json
Gruntfile.js
dist
*.iml
````

Thanks for your efforts on this, Nice Job!!
