### ISSUE TITLE
config does not pull default region from the environment

### ISSUE THREAD

**Issue by donleyp** [Tim-B/grunt-aws-lambda#18]
In the Lambda environment the default region used by the AWS SDK is the region in which the Lambda function is running. In the grunt-aws-lambda environment when running the task locally the region is not set. I have the region specified in ~/.aws/config as us-west-2 but it is not picking it up from there.

Here is the error thrown by the AWS SDK when I try to make a call to CloudWatchLogs api:
{ [ConfigError: Missing region in config]
  message: 'Missing region in config',
  code: 'ConfigError',
  time: Fri Jul 03 2015 21:37:54 GMT-0700 (PDT) }

**Comment by donleyp** [comment]
I worked around this by putting this code at the top of my Gruntfile.js:
```javascript
var AWS = require('aws-sdk')
AWS.config.region = 'us-west-2'
```

**Comment by Tim-B** [comment]
Hi @donleyp, thanks for raising this issue.

I was taking a look and I think the core issue is that the JS AWS SDK doesn't read the region from ~/.aws/config like the CLI does.

There's a bit of discussion about it [here](https://github.com/aws/aws-sdk-js/issues/473) and I also looked at [the source](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/shared_ini_file_credentials.js#L71) and it seems only the key, secret and session token are read.

However you should also be able to get around this issue by setting the `AWS_REGION` environment variable before running `lambda_invoke`, which I assume is how the region is passed to the SDK in the actual Lambda environment. Your solution should work fine too.

Another solution I'm considering is setting the `AWS_REGION`  environment variable automatically according to a Gruntfile configuration option, but I need to think about whether that might cause any side effects for users first.

**Comment by cyxou** [comment]
Same problem here, but putting @donleyp's code at the top of my Gruntfile.js did not work for me.

**Comment by Tim-B** [comment]
Did setting the environment variable work for you?

If you don't need to deploy the function to multiple regions you should also just be able to specify the region within your lambda function, for example:

```
exports.handler = function(event, context) {
    AWS.config = {
        region: 'us-east-1'
    };
    var s3 = new AWS.S3();
```

**Comment by jvwing** [comment]
I also had a similar but different AWS region problem when running the lambda_deploy task.  I was unable to get either the `AWS.config.update({"region": "us-west-2"})` or the `AWS_REGION` environment variable solution to work (I tried both setting the variable in a bash shell, and as part of the grunt task using grunt-env).  

However, it appears that the lambda_deploy task supports **options.region** that does correctly configure the AWS instance used in the deploy.

```javascript
lambda_deploy: {
    default: {
        options: {
            memory: 128,
            region: "us-west-2"
        },
        arn: "arn:aws:lambda:us-west-2:123456789012:function:foo"
    }
}
```

In b92dd4d9899cb76e7a29358a0f4ed8f87519119b, the documentation for this option was removed from README.md, but the code was kept in lambda_deploy.js.  May I send a pull request to add that back?  Also, we should be able to parse the region out of the ARN, when the function is specified by ARN.  Any interest in a pull request for that?

**Comment by Tim-B** [comment]
@jvwing I can't think of any reason why the region documentation was removed so it must have been a mistake.

I'm assuming the SDK doesn't automatically figure out the region automatically? I [can't see anything about it in the docs](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#updateFunctionConfiguration-property), but I haven't explicitly tested it yet. That's the only reason I can think why I might have removed those docs.

Assuming the SDK doesn't figure it out automatically, a pull request for that feature sounds great!
