### ISSUE TITLE
"Cannot find module 'npm'"

### ISSUE THREAD

**Issue by timdp** [Tim-B/grunt-aws-lambda#20]
I use npm@3.1.2. Using grunt-aws-lambda gives me:

```
Loading "lambda_package.js" tasks...ERROR
>> Error: Cannot find module 'npm'
>>     at Function.Module._resolveFilename (module.js:336:15)
>>     at Function.Module._load (module.js:278:25)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.module.exports (node_modules\grunt-aws-lambda\tasks\lambda_package.js:14:15)
```

Looks like `require('npm')` no longer works by default with npm 3.

`npm i npm@3.1.2` fixes it, so you can probably just include npm in the dependencies. No idea how you would elegantly pass the version of the globally installed npm though. A postinstall hook would work, I guess.

**Comment by Tim-B** [comment]
Hi @timdp, thanks for the report!

Can you confirm you're using the latest version of this plugin (ie. 0.8.0)? npm was added to the `devDependencies` a few versions back which solved some similar issues a few people were having.

I also installed NPM 3.1.2 and it seems to be working okay for me.

**Comment by timdp** [comment]
Thanks for the quick response!

Won't `devDependencies` only get installed if I install my own module with `--dev`? That's not something I'm eager to do.

Is there a reason why it's not a regular dependency?

**Comment by Tim-B** [comment]
My understanding is that `devDependencies` should get installed by a regular `npm install` unless you add the `--production` flag.

If you are using the latest version you could try moving it to regular dependencies, I'd be interested to know if that helps.

**Comment by timdp** [comment]
Pretty sure that that's not how it works. Installing devDependencies for all dependencies by default would mean a hell of a lot of modules to install. For example, for every module that depends on PhantomJS for browser testing, you'd then unzip PhantomJS again. Particularly with npm 2's non-flattened node_modules folder, you'd waste a _lot_ of disk space on modules that never get used, since you'd never run the tests for your dependencies; that's the author's job.

I verified this by just running `npm init && npm i --save grunt grunt-aws-lambda` in a new folder. It created neither node_modules/npm nor node_modules/grunt-aws-lambda/node_modules/npm. With `--save-dev` rather than `--save`, I got the same result. The only difference between those two flags is how it updates package.json, I think.

**Comment by timdp** [comment]
Maybe you're getting confused by how `npm i` works from _inside_ your module's folder? It _will_ install both dependencies and devDependencies for ./package.json, but not for _their_ dependencies.

**Comment by Tim-B** [comment]
Yeah you're right, I was thinking of the situation where the module was being installed directly as opposed to being installed as a dependency.

Truth be told I was never able to replicate the issue, however someone submitted a pull request saying adding npm to `devDependencies` fixed it for them. The change didn't cause any tests to fail and didn't seem to have any side effects so I accepted it.

So does adding npm as a regular dependency help your issue?

**Comment by timdp** [comment]
It most likely would. I'm at work now, but I'll test soon.

**Comment by peterfox** [comment]
I had an issue with this on my Mac, just had to add 
export NODE_PATH='/usr/local/lib/node_modules' 

to my ~/.bash_profile and it worked fine afterwards.

**Comment by timdp** [comment]
That sounds like a different issue to me.

**Comment by timdp** [comment]
Making npm a regular dependency worked for me.

I initially tried with npm@^3.2.0, but that failed. I'll make a new issue for documenting my findings.
