### ISSUE TITLE
lambda_invoke swallows error stacktrace

### ISSUE THREAD

**Issue by shin-nien** [Tim-B/grunt-aws-lambda#30]
When developing functions and invoking them using lambda_invoke, error (e.g. parse errors) stacktraces are getting swallowed up and I'm just getting the error string.

Is there a way to get the full trace? Thanks.

**Comment by Tim-B** [comment]
Have you tried using the `--stack` grunt flag?

**Comment by shin-nien** [comment]
Ahhh no I didn't! I'm new to grunt. Thanks and thanks for writing the plugin.
