### ISSUE TITLE
Finding bundledDependencies

### ISSUE THREAD

**Issue by tinkyholloway** [Tim-B/grunt-aws-lambda#32]
(I'm new at all this, so it's likely that I am doing something fundamentally wrong.)

My source tree look like this:

    /Gruntfile.js
    /package.json 
    /node_modules/..../blah
    /function1/index.js
    /function1/package.json
    /function2/index.js
    /function2/package.json
    /common/dependency_package/index.js
    /common/dependency_package/package.json

`dependency_package` has been added to the `dependencies` and `bundledDependencies` sections of `function1/package.json` and `function2/package.json`.

I've installed `dependency_package` in `/` so it is in `/node_modules/`

When I run the `lambda_invoke` task everything works fine.

When I package with `lambda_package`, the task executes with no warning or error, but `dependency_package` is not included in the zip file. To have it included in the zip file I need to go into `/function1/` and `/function2/` directories and run `npm install` there.

I was hoping that `grunt-aws-lambda` would find the package by inspecting up the directory tree like `require` does. Failing that I was hoping that the plugin would issue an error if it cannot find `bundledDependencies` when building the zip.

**Comment by Tim-B** [comment]
It looks like you're trying to have multiple functions within a single project. I posted some advice about that use case here: https://github.com/Tim-B/grunt-aws-lambda/issues/29#issuecomment-127676590
