### ISSUE TITLE
Support handler in lambda-deploy

### ISSUE THREAD

**Issue by flyingsky** [Tim-B/grunt-aws-lambda#33]
Because you support file-name in lambad-invoke, so I can use other js file name, not default index.js. But if I use customized js file name, it doesn't work after deploy, because js file name is changed. To support it you have to support "handler" in lambda-deploy.

**Comment by Tim-B** [comment]
I think you might need to change the handler settings for your function, by default it's `index.handler` but according to the documentation in the AWS console the first component is the file name:

```
The module-name.export value in your function. For example, "index.handler" would call exports.handler in index.js.
```

**Comment by flyingsky** [comment]
Yes, I have to change handler settings. Unfortunately this plugin deploy function doesn't support to change handler setting.

**Comment by Tim-B** [comment]
Once you set the handler manually in the function settings does it persist after you deploy? It should leave any unsupported settings unchanged when deploying.

Adding support to set the handler is probably still a good idea though.
