### ISSUE TITLE
Fatal error in v8

### ISSUE THREAD

**Issue by objectiveSee** [Tim-B/grunt-aws-lambda#36]
Anyone else seeing this error on `grunt deploy`? It happens intermittently. I am also seeing very long times at `Running "lambda_package:default" (lambda_package) task` and very large packages (> 1GB) despite my codebase being quite a bit smaller.

```
Running "lambda_deploy:default" (lambda_deploy) task
Uploading...


#
# Fatal error in ../deps/v8/src/handles.h, line 48
# CHECK(location_ != NULL) failed
#

==== C stack trace ===============================

 1: ??
 2: ??
 3: ??
 4: ??
 5: ??
 6: ??
 7: ??
 8: ??
Illegal instruction: 4
```

**Comment by Tim-B** [comment]
Thanks for bringing this up!

I've done some Googling and this appears to suggest running out of memory.

Does it give you any further details if you run it with the `--stack` grunt flag?

I'm trying to figure out if it's the zipping or the copying the zip which is causing this.

Also, it might help to know what version of node you're running and how much memory your system has (ie. are you running it on a very memory limited VM?).

Out of interest, do you have a strong need to make your packages that big? Ie. do you need to include large static files (eg. a lookup table) or do you just have a lot of dependencies?

**Comment by objectiveSee** [comment]
I will start running with `--stack` and let you know if I catch the issue again. I just updated `npm`, and `grunt-cli`, and have been running Node v0.12.5.

The >1GB .zip files is strange as nothing in my project comes close to being 1GB. There's no need for this to be a large project. `./node_modules/` is 38 MB, and the rest of my project is < 2MB. 

Also to note, the command works sometimes. When it fails, it takes a long time to get through the package and/or deploy steps. When it works, it's much faster.

**Comment by objectiveSee** [comment]
Hey Tim, turns our I didn't RTFM enough to see your mention about `.npmignore`. I added `dist` to that file which I'm guessing will fix my issues. Will post back if I see the issue persist.

**Comment by Tim-B** [comment]
Ah yes, that's an easy trap to fall into. I was thinking about doing something to automatically add `dist` to NPMs ignore list, but I'd want to do it in a way which doesn't mess to much with the NPM internals.
