### ISSUE TITLE
Update aws-sdk dependency

### ISSUE THREAD

**Issue by thedevkit** [Tim-B/grunt-aws-lambda#41]
AWS Lambda has moved its supported version of 'aws-sdk' to 2.2.3, while this project still shows a dependency on version ~2.1.30. It's quite annoying to have to see all the "unmet dependency" output when using npm.

Looking through the documentation, it doesn't look like there is anything between 2.1.35 and 2.2.3 that would cause the functionality to break. Can we please get a dependency version update?

**Comment by analytically** [comment]
:+1:

**Comment by Tim-B** [comment]
The SDK will be bumped to `2.2.32` in the next release.
