### ISSUE TITLE
Only include a single JS file and node_modules in distribution?

### ISSUE THREAD

**Issue by jakelodwick** [Tim-B/grunt-aws-lambda#42]
Hey Tim, loving this repo... saving me a bunch of time & the documentation is great.

One suggestion. According to [this AWS Lambda docs page](http://docs.aws.amazon.com/lambda/latest/dg/walkthrough-s3-events-adminuser-create-test-function-create-function.html), a Lambda deployment package only needs to contain a single JS file and the relevant node_modules. But it looks like this repo's `lambda_package` method is bundling other stuff from the project folder.

I'm able to bypass most of them with my `.npmignore` file, but `package.json` is still included. I don't think it's necessary here unless I'm missing something. Lambda seems to ignore these extraneous files, but it might be better to not include them in the first place.

This could be a good candidate for my first pull request. Maybe I can take a crack at it. Just LMK if I'm missing something...

**Comment by Tim-B** [comment]
I agree that the `package.json` isn't necessary, and it's probably unlikely any existing users are depending on it being bundled with their functions.

Can you think of any situations where having it there might actually cause an issue besides adding a few kb of overhead?

**Comment by jakelodwick** [comment]
I can't!

**Comment by Tim-B** [comment]
Closing this issue as I think it's a fairly low priority, but if anyone runs into a use case where this is a more serious problem then feel free to reopen.
