### ISSUE TITLE
Simulate context.clientContext for local invocation/testing

### ISSUE THREAD

**Issue by Skorch** [Tim-B/grunt-aws-lambda#47]
Are there any options to inject an object into the context called clientContext?  The native mobile SDKs pass this in, which has device information, etc, as well as the local AWS Cognito identifier.  This is the sort of information that will become more and more common once mobile developers start calling into Lambdas natively.

http://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_RequestSyntax
http://docs.aws.amazon.com/mobileanalytics/latest/ug/PutEvents.html

**Comment by Tim-B** [comment]
Thanks, didn't realise this had been added. I'll try and add this when I have time (although pull a pull request would also be welcome).

In the mean time you could test if it's undefined and if it is set some test data so you're not completely unable to test locally.

**Comment by mseiwald** [comment]
+1 We are accessing context.functionVersion in the Lambda code. Would be highly appreciated if the ability to customize the context object was added.

**Comment by Skorch** [comment]
I created. Pull Request a while back. It has been working well for me. 

https://github.com/Tim-B/grunt-aws-lambda/pull/51

**Comment by Tim-B** [comment]
This will be included in the next release, thanks for raising this issue!
