### ISSUE TITLE
Why this plugin doesn't support proxy configuration

### ISSUE THREAD

**Issue by malexiaofei** [Tim-B/grunt-aws-lambda#48]
Could you add the httpOptions in Options?
http://blogs.aws.amazon.com/javascript/post/Tx3CV0OSVN2TBPS/Using-the-AWS-SDK-for-JavaScript-from-Behind-a-Proxy
When I try to deploy lambda function behind proxy server, it's always failed.
Or should I open a new PR for this? 
Just add the proxy string for options will influence the dependencies. It will require proxy-agent.

**Comment by Tim-B** [comment]
Feel free to submit a pull request.

Maybe it would be best to be able to pass a full HTTP agent via the grunt options, that way the user can pass an agent for other purposes besides using a proxy.
