### ISSUE TITLE
Objects passed to the context output methods aren't serialized

### ISSUE THREAD

**Issue by jkells** [Tim-B/grunt-aws-lambda#54]
It's common to call `context.succeed` `context.error` and `context.done` with an object instead of a string.

The lambda invoke task fails to output them, instead just printing the following
```
Success!  Message:
------------------
[object Object]
```

I think the output objects should be serialized so you get some sane output.

**Comment by pedrocarrico** [comment]
According to the [AWS Lambda documentation](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html) the result provided must be JSON.stringify compatible so :+1: for #55

**Comment by Tim-B** [comment]
Thanks for reporting this issue.

It should be resolved by this pull request in the next release: https://github.com/Tim-B/grunt-aws-lambda/commit/f544e425d906196611b3068b9e07ef2c13e1f121
