### ISSUE TITLE
using ~/.aws/credentials or environmental variables

### ISSUE THREAD

**Issue by niallrobinson** [Tim-B/grunt-aws-lambda#61]
Hi all,

I want to use this as part of my Travis CI setup. In practice this means I'd like to provide AWS credentials using my `~/.aws/credentials` file when deploying locally, but using environmental variables when deploying on Travis. Is there any way to do this currently?

Thanks

**Comment by Tim-B** [comment]
Hi Niall, have you tried this?

My understanding is that if no other credentials are supplied the SDK will try a chain of credential providers. I think it tries `~/.aws/credentials` then the environment, so it may work already.

If not you could always have multiple deploy configurations in your grunt file and run one target locally and a different one from travis.

**Comment by niallrobinson** [comment]
Hi @Tim-B - thanks for the response. What I've ended up doing is using my credentials locally, but if the script can find them, it goes to the envs, as you say. That seems to work.
