### ISSUE TITLE
lambda_deploy fails if the function has not been created before

### ISSUE THREAD

**Issue by danapsimer** [Tim-B/grunt-aws-lambda#7]
The lambda_deploy task fails because it executes a getFunction before uploading the packaged zip file.

Since the UploadFunction method is used to create and update functions, failing on a 404 response from the getFunction call is probably not the best practice.

**Comment by danapsimer** [comment]
After looking at this further, it seems what is really needed is the ability to pass in the role, mode, runtime, and handler parameters so that a create can succeed.

**Comment by Tim-B** [comment]
Hi danapsimer,

Have you created the function first?

The role, mode, runtime, etc. should be set here: https://github.com/Tim-B/grunt-aws-lambda/blob/master/tasks/lambda_deploy.js#L60

It just reuses the existing function settings. Currently it doesn't make new functions or manage the function settings, just deploy to an existing function.

Cheers, Tim.

**Comment by JimW** [comment]
http://docs.aws.amazon.com/cli/latest/reference/lambda/create-function.html
Would be nice.. Maybe if I get some time..
