### ISSUE TITLE
[Feature request] Support Lambda Node.js 4.32

### ISSUE THREAD

**Issue by agarstang** [Tim-B/grunt-aws-lambda#77]
Implement support for latest Lambda Node.js 4.32 release and the callback method functionality that is replacing the context object.

https://aws.amazon.com/blogs/compute/node-js-4-3-2-runtime-now-available-on-lambda/

**Comment by nmaves** [comment]
Would you accept a PR on this?

**Comment by agarstang** [comment]
I would be interested to see how you would do it. I looked into it and could implement most of the functionality however I was unsure on intricacies of the "callbackWaitsForEmptyEventLoop" setting.

**Comment by agarstang** [comment]
#76 :+1:

**Comment by Tim-B** [comment]
Pull request #76 has been merged and included in the release I just published.
