### ISSUE TITLE
context.succeed() and context.fail() when using lambda_invoke

### ISSUE THREAD

**Issue by jonyo** [Tim-B/grunt-aws-lambda#8]
When you use `grunt lambda_invoke` on even the hello world script, it gives the error:
```sh
$ grunt lambda_invoke:HelloWorld
Running "lambda_invoke:HelloWorld" (lambda_invoke) task

Loading function
value1 = First Value
value2 = Second Value
value3 = Third Value
Warning: undefined is not a function Use --force to continue.

Aborted due to warnings.
```

I found the issue is that `context.succeed` function is not defined in the invoke.

Is this project still active?  If so I can submit a PR to fix this by fully mocking the context object as documented in the AWS Lambda docs.  Thanks!

**Comment by Tim-B** [comment]
Yeah it's still active, I'm just a bit busy at the moment so I haven't had much time to sort through the issues.

I didn't notice they'd added succeed() and fail() functions, initially it was just done() I think.
